### ISSUE TITLE
about  the  formula (6) in the paper, 

### ISSUE THREAD

**Issue by sehb** [PRBonn/kinematic-icp#24]
is there a detailed derivation process?

**Comment by benemer** [comment]
$f(u)$ is the integrated kinematic model, for which you could use, for example, the Euler or Runge-Kutta integration schemes for a unicycle model. We explicitly modeled the differential drive and the derivation can be found in G. Grisetti's lecture [slides](https://www.google.com/url?q=https%3A%2F%2Fgitlab.com%2Fgrisetti%2Fprobabilistic_robotics_2018_19%2Fblob%2Fmaster%2Fslides%2Fprobabilistic_robotics_19_least_squares_odometry_calibration.pdf&sa=D&sntz=1&usg=AOvVaw39aqjHFqDTlQ4JuHIY64dw) on odometry calibration:

![image](https://github.com/user-attachments/assets/1173177b-5723-4e46-89e9-18590b2ee091)

You have to insert the expression for $R$ and replace the term $\frac{r+l}{2}$ by our forward motion $\Delta x$.

**Comment by sehb** [comment]
detax is not linear displancement,  it's the arc that the reference cental moved.  If detatheta is small, maybe approximately equal

**Comment by benemer** [comment]
Originally, $\frac{r+l}{2}$ is the traveled distance of your rear axis center computed from the average traveled distances $r$ and $l$ of both wheels measured with the encoder ticks. In our case, $\Delta x$ is the integrated velocity control in the forward $x$-direction of the robot's local base frame. Since this base frame can rotate, the resulting integrated path can be an arc.

**Comment by sehb** [comment]
Thanks！
